print("start PSI purge");
# remove item recipes
recipes.remove(<psi:material:*>);
recipes.remove(<psi:cadCore:*>);
recipes.remove(<psi:cadColorizer:*>);
recipes.remove(<psi:cadSocket:*>);
recipes.remove(<psi:cadBattery:*>);
recipes.remove(<psi:cadAssembly:*>);
recipes.remove(<psi:cadAssembler:*>);
recipes.remove(<psi:programmer>);
recipes.remove(<psi:psimetalSword>);
recipes.remove(<psi:cadAssembly>);
recipes.remove(<psi:exosuitSensor:*>);
recipes.remove(<psi:psimetalPickaxe>);
recipes.remove(<psi:psimetalShovel>);
recipes.remove(<psi:psimetalAxe>);
recipes.remove(<psi:psimetalExosuitHelmet>);
recipes.remove(<psi:psimetalExosuitChestplate>);
recipes.remove(<psi:psimetalExosuitBoots>);
recipes.remove(<psi:psimetalExosuitLeggings>);
recipes.remove(<psi:spellBullet:*>);
recipes.remove(<psi:spellBullet:*>);
recipes.remove(<psi:detonator>);
recipes.remove(<psi:spellDrive>);
recipes.remove(<psi:exosuitController>);
recipes.remove(<psi:conjured>);
recipes.remove(<psi:psiDecorative:*>);
# flag banned items
<psi:material:*>.addTooltip(format.red("ThePeak - BANNED"));
<psi:cadCore:*>.addTooltip(format.red("ThePeak - BANNED"));
<psi:cadColorizer:*>.addTooltip(format.red("ThePeak - BANNED"));
<psi:cadSocket:*>.addTooltip(format.red("ThePeak - BANNED"));
<psi:cadBattery:*>.addTooltip(format.red("ThePeak - BANNED"));
<psi:cadAssembly:*>.addTooltip(format.red("ThePeak - BANNED"));
<psi:cadAssembler:*>.addTooltip(format.red("ThePeak - BANNED"));
<psi:programmer>.addTooltip(format.red("ThePeak - BANNED"));
<psi:psimetalSword>.addTooltip(format.red("ThePeak - BANNED"));
<psi:cadAssembly>.addTooltip(format.red("ThePeak - BANNED"));
<psi:exosuitSensor:*>.addTooltip(format.red("ThePeak - BANNED"));
<psi:psimetalPickaxe>.addTooltip(format.red("ThePeak - BANNED"));
<psi:psimetalShovel>.addTooltip(format.red("ThePeak - BANNED"));
<psi:psimetalAxe>.addTooltip(format.red("ThePeak - BANNED"));
<psi:psimetalExosuitHelmet>.addTooltip(format.red("ThePeak - BANNED"));
<psi:psimetalExosuitChestplate>.addTooltip(format.red("ThePeak - BANNED"));
<psi:psimetalExosuitBoots>.addTooltip(format.red("ThePeak - BANNED"));
<psi:psimetalExosuitLeggings>.addTooltip(format.red("ThePeak - BANNED"));
<psi:spellBullet:*>.addTooltip(format.red("ThePeak - BANNED"));
<psi:detonator>.addTooltip(format.red("ThePeak - BANNED"));
<psi:spellDrive>.addTooltip(format.red("ThePeak - BANNED"));
<psi:exosuitController>.addTooltip(format.red("ThePeak - BANNED"));
<psi:conjured>.addTooltip(format.red("ThePeak - BANNED"));
<psi:psiDecorative:*>.addTooltip(format.red("ThePeak - BANNED"));
print("End PSI purge");